### ISSUE TITLE
数据集115网盘没法注册登陆

### ISSUE THREAD

**Issue by liujianzhao6328057** [kekezhang112/SISAR-DISQ#1]
您好，115网盘显示系统升级维护，现在没法登陆下载，可以方便更新其他网盘的下载链接吗

**Comment by kekezhang112** [comment]
谢谢您的关注。麻烦您稍后再试一下，很抱歉近期我无暇上传其他网盘。如果还不能下载，麻烦两周后再联系我，感谢理解。

**Comment by liujianzhao6328057** [comment]
> 谢谢您的关注。麻烦您稍后再试一下，很抱歉近期我无暇上传其他网盘。如果还不能下载，麻烦两周后再联系我，感谢理解。

您好，现在可以下载了。还有个论文中的问题想请教您，请问一下论文中DS-SR iterations 中的iteration指的是低分辨图超分后然后再降采样再超分再降采样再超分吗

**Comment by kekezhang112** [comment]
> > 谢谢您的关注。麻烦您稍后再试一下，很抱歉近期我无暇上传其他网盘。如果还不能下载，麻烦两周后再联系我，感谢理解。
> 
> 您好，现在可以下载了。还有个论文中的问题想请教您，请问一下论文中DS-SR iterations 中的iteration指的是低分辨图超分后然后再降采样再超分再降采样再超分吗

您好，很抱歉回复晚了。迭代过程是高分辨率图像先降采样再超分辨，然后再降采样再超分辨等等这样的过程。

**Comment by chicken854** [comment]
您好，可以方便更新其他网盘的下载链接吗
