### ISSUE TITLE
Asking for help in model implementation.

### ISSUE THREAD

**Issue by Gray-OREO** [kekezhang112/SISAR-DISQ#2]
Hi @kekezhang112 ,

It's an interesting work in SR-IQA, but I have some questions for DISQ:

1. To my knowledge, QADS doesn't provide the LR images, how can I get the LR images for model training?

2. In SISAR, various LR images with different down-sampling factors are provided, so which kind of the LR image is used for the LR branch ?  

Thanks for your reading ~ 😊

**Comment by kekezhang112** [comment]
Hi, 
Thank you for your interest  in our work.
1. Please refer to the QADS paper, the authors declare that "To obtain the distorted images, we first use bicubic down-sampling to reduce the size of the reference images by a factor of k (k=2,3,4)".
2. All LR images are used for LR branch. Please refer to the released code for details.

**Comment by Gray-OREO** [comment]
Thanks for your quick reply, it's very useful !
